### ISSUE TITLE
Is it possible to run PrivMRF without a GPU?

### ISSUE THREAD

**Issue by sfc-gh-mholboke** [caicre/PrivMRF#1]
Can I run PrivMRF without a GPU?
If so what changes would I need to make?
Thank you

**Comment by caicre** [comment]
Hi, thanks for your interest. You may try to replace cupy with numpy, and replace all the cp.get_array_module with np. I believe this will work on CPUs.

**Comment by sfc-gh-mholboke** [comment]
That's what I did - thanks though
