### ISSUE TITLE
SVD factor normalization

### ISSUE THREAD

**Issue by Ulfzerk** [caicre/PrivMRF#5]
Hi! 

I'm trying to understand your paper with code.

There is a function dp_TVD in tools.py
It calculates total variation distance between distributions of pair of attributes. 
I assume that it stands for R_score from your paper. 

Fragment of `dp_TVD(TVD_map, data, domain, index_list, noise):`
```python
histogram, _= np.histogramdd(data[:, index_list], bins=bins)
fact1 = Factor(domain, histogram, np)
# print('!', domain.shape, '!', bins, '!', histogram.shape)

temp_domain = domain.project([index_list[0]])
temp_index_list = temp_domain.attr_list
histogram, _= np.histogramdd(data[:, temp_index_list], bins=temp_domain.edge())
fact2 = Factor(temp_domain, histogram, np)

temp_domain = domain.project([index_list[1]])
temp_index_list = temp_domain.attr_list
histogram, _= np.histogramdd(data[:, temp_index_list], bins=temp_domain.edge())
fact3 = Factor(temp_domain, histogram, np)

data_num = len(data)
fact4 = fact2.expand(domain) * fact3.expand(domain) / data_num
TVD = np.sum(np.abs(fact4.values - fact1.values)) / 2 / data_num
```

fact1.values is never normalized by data_num but fact4 is. 
So we are we subtract a unnormalized fact1 which can have very high values from fact4 which is in range 0 to 1. 

Is it how it was supposed to work?

**Comment by caicre** [comment]
Hi, [Ulfzerk](https://github.com/Ulfzerk). fact4 is the product of fact2 and fac3, which are both unnormalized. So fact4 is not normalized too (even if it is divided by data_num).
